#!/usr/bin/env python3
"""Convert split manifests with scenes as strings into dict-style scene manifests.

Input example generated by early B-fast renderer:
  {"scenes": ["/abs/path/scene_00000.npz", ...]}

Output:
  {"scenes": [{"scene_id": "scene_00000", "scene_npz": "/abs/path/scene_00000.npz"}, ...]}
"""
import argparse
import json
from pathlib import Path


def fix_one(path: Path, overwrite: bool = True) -> None:
    data = json.loads(path.read_text(encoding="utf-8"))
    scenes = data.get("scenes", data if isinstance(data, list) else None)
    if scenes is None:
        raise ValueError(f"Unsupported manifest format: {path}")
    fixed = []
    changed = False
    for s in scenes:
        if isinstance(s, str):
            p = Path(s)
            fixed.append({"scene_id": p.stem, "scene_npz": s})
            changed = True
        else:
            fixed.append(s)
    if isinstance(data, dict):
        data["scenes"] = fixed
        out_data = data
    else:
        out_data = fixed
    out_path = path if overwrite else path.with_suffix(path.suffix + ".fixed")
    out_path.write_text(json.dumps(out_data, indent=2), encoding="utf-8")
    print(f"{path}: {'fixed' if changed else 'already ok'} -> {out_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("paths", nargs="+", help="manifest json files or a directory containing train/val/test.json")
    ap.add_argument("--no_overwrite", action="store_true")
    args = ap.parse_args()
    files = []
    for p in map(Path, args.paths):
        if p.is_dir():
            files.extend([p / "train.json", p / "val.json", p / "test.json"])
        else:
            files.append(p)
    for f in files:
        if f.exists():
            fix_one(f, overwrite=not args.no_overwrite)
        else:
            print(f"skip missing: {f}")


if __name__ == "__main__":
    main()
